#!/usr/bin/env python3

import sys
import os
import helpers
from analyzer import Analyzer
from termcolor import colored

def main():
    
    if len(sys.argv)!=2:
        sys.exit("Usage: ./tweets @screen_name")
    else:
        L=helpers.get_user_timeline(sys.argv[1],count=50)
        l=[]
        positives = os.path.join(sys.path[0], "positive-words.txt")
        negatives = os.path.join(sys.path[0], "negative-words.txt")
        b=Analyzer(positives,negatives)
        for text in L:
            l.append(b.analyze(text))
            if b.analyze(text)>0:
                print(colored(str(b.analyze(text))+' '+text,"green"))
                #l.append(colored(text,"green"))
            elif b.analyze(text)<0:
                print(colored(str(b.analyze(text))+' '+text,"red"))
                #l.append(colored(text,"red"))
            else:
                print(colored(str(b.analyze(text))+' '+text,"yellow"))
                #l.append(colored(text,"yellow"))
         
                
        
if __name__ == '__main__':
    main()
